### ISSUE TITLE
这个播放器 在手机微信上以及 Safari上 都不支持吗

### ISSUE THREAD

**Issue by jayfirst** [huajiaofrontend/HJPlayer#1]
我做了个demo 上面 不支持微信   很尴尬 Safari上也不好使

**Comment by lijingan** [comment]
手机上不支持mse ，不可能使用哟。另外手机端本身支持m3u8的直接播放。不是这个项目的应用场景哟。

**Comment by flyland68** [comment]
那在手机浏览器里，比如微信，safari里，如何支持sei呢？
