### ISSUE TITLE
播放hls直播的时候报错

### ISSUE THREAD

**Issue by yay2008** [huajiaofrontend/HJPlayer#2]
![20200114170504](https://user-images.githubusercontent.com/4987371/72329626-10323c00-36f0-11ea-9313-55c744f5bce1.jpg)

hjplayer.js:1 Uncaught TypeError: Cannot read property 'fragments' of undefined
    at t.onManifestParsed (hjplayer.js:1)
    at h.emit (hjplayer.js:1)
    at e._handleMasterPlaylist (hjplayer.js:1)
    at e.loadSuccess (hjplayer.js:1)
    at e.readystatechange (hjplayer.js:1)
t.onManifestParsed @ hjplayer.js:1
h.emit @ hjplayer.js:1
e._handleMasterPlaylist @ hjplayer.js:1
e.loadSuccess @ hjplayer.js:1
e.readystatechange @ hjplayer.js:1
XMLHttpRequest.send (async)
e.loadInternal @ hjplayer.js:1
e.load @ hjplayer.js:1
e.load @ hjplayer.js:1
t.open @ hjplayer.js:1
t.startLoad @ hjplayer.js:1
e.open @ hjplayer.js:1
e._loadSegment @ hjplayer.js:1
e.start @ hjplayer.js:1
e.open @ hjplayer.js:8
e.load @ hjplayer.js:8
(anonymous) @ hjplayer.js:8
h.emit @ hjplayer.js:1
e._onSourceOpen @ hjplayer.js:8
hls.js 播放正常

**Comment by happyLjc** [comment]
能否提供HLS流地址或者M3U8文档的内容, 我需要查看一下解析后的文档

**Comment by yay2008** [comment]
m3u8的内容如下,里面的地址可以播放(url已修改)但是有个错误
![20200115195954](https://user-images.githubusercontent.com/4987371/72432369-d5a0d000-37d1-11ea-89a2-cd831267ec7b.jpg)


#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=10000000
http://3739115309.cloudvdn.com/a.m3u8?domain=pili-live-hls.live.ykd.com&player=dn0AAMXFdzhGDeoV&secondToken=secondToken%3AbIvH_g_daN0jtFFIevdVPSeka_U&streamid=ykd%3Aykd%2F13&v3=1

**Comment by happyLjc** [comment]
我这403无法访问, 能把M3U8文件里的内容发上来吗

**Comment by yay2008** [comment]
https://3739115326.cloudvdn.com/a.m3u8?domain=pili-live-hdl.live.yunkaodian.com&player=bCQAAMhgi82gO-oV&secondToken=secondToken%3A5nwexCqiJH-JhoX709SlqrN6l6Q&streamid=yunkaodian%3Ayunkaodian%2F62&v3=1   有效期只有半天

**Comment by lijingan** [comment]
你俩可以加个微信。。。方便更快的沟通吧 :)

**Comment by yay2008** [comment]
微信 yay2008

**Comment by happyLjc** [comment]
1.0.4已解决,  在判断masterPlaylist和singleLevelList时出错, 已更正
